
services:
  substreams-sink:
    build:
      context: .
      args:
        TELLER_GITHUB_REPO: https://github.com/teller-protocol/teller-protocol-v2.git
        DSN: ""
        SUBSTREAMS_API_TOKEN: ""
        EVM_NETWORK_NAME: ""
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
